### ISSUE TITLE
Git certificate error when running install_ace.sh

### ISSUE THREAD

**Issue by tanoury1** [duartegroup/mlp-train#74] opened 2023-11-29 20:49 UTC
Hi,
I'm getting a BADCERT_NOT_TRUSTED error for pyjulip when executing install_ace.sh.  I am able to clone pyjulip at the address in the yaml file via commandline (when using https://github.com/casv2/pyjulip.git), but not when running the script.  Error output is attached. 

 Also, it appears that the https://github.com/casv2/pyjulip.git@72280a6ac3  repo does not exist (hence cloning from the most recent repo version).

Best regards,
Jerry
[ace-error.txt](https://github.com/duartegroup/mlp-train/files/13505345/ace-error.txt)

**Comment by juraskov** [comment] 2023-12-05 09:42
Hi Jerry, I could not reproduce your error on my computer. Do you install it on a different machine than before? What version of Julia do you use? I found this discussion https://github.com/JuliaLang/Downloads.jl/issues/97 It might be worth asking the system administrators about the certificates. Also, the link you provide is not supposed to work alone, it is only for the installation. It points to pyjulip commit 72280a6ac3, which is still there, i.e. here: https://github.com/casv2/pyjulip/tree/72280a6ac3f0b4107fe73637fb409b0c42e9011d and should be used. If you cloned the last repository, you can run:

```
git checkout 72280a6ac3
```
to change to the required commit and install it through pip again.

Best wishes,

Veronika

**Comment by tanoury1** [comment] 2023-12-05 15:07
Thank you Veronica.  I'm using Julia 1.6.7.  There seems to be some issues
with the certificates on the cluster I'm using.
If I understand building mlp-train correctly, I need 3 separate conda
environments: mlptrain-ace, mlptrain-gap, mlptrain-mace.  Will this
workaround work?
1. truncate environment_ace.yml below 'xtb'.
2. run install_ace.sh using the truncated yml file.
3. activate the mlptrain-ace environment
4. while in that environment, run 'pip install julia', then clone the
specific commits for pyjulip and ace.
5. repeat this for gap and mace.

All the best,
Jerry

**Comment by tanoury1** [comment] 2023-12-05 16:59
Hi again,
Solved it by running: 'env GIT_SSL_NO_VERIFY=true pip install git+
***@***.***'

**Comment by juraskov** [comment] 2023-12-05 17:02
Great, thanks for reporting back! I will close the issue now. 

Veronika

**Closed by juraskov** 2023-12-05 17:02 UTC
